services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shibatalk-backend
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - shibatalk-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shibatalk-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - shibatalk-network

networks:
  shibatalk-network:
    driver: bridge
