import { StyleSheet } from "react-native";
export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f7fafd",
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderColor: "#e3e6eb",
    backgroundColor: "#fff",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 2,
  },
  headerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#e3e6eb",
  },
  headerText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#222",
    letterSpacing: 0.2,
  },
  messageList: {
    flex: 1,
    paddingHorizontal: 10,
  },
  inputContainer: {
    padding: 10,
    borderTopWidth: 1,
    borderColor: "#e3e6eb",
    backgroundColor: "#fff",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f2f4f7",
    borderRadius: 24,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  input: {
    flex: 1,
    height: 40,
    borderWidth: 0,
    borderRadius: 20,
    paddingHorizontal: 12,
    backgroundColor: "#f2f4f7",
    fontSize: 15,
    color: "#222",
    marginRight: 8,
  },
  iconButton: {
    padding: 5,
    marginRight: 2,
  },
  emojiModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 10,
    maxHeight: "50%",
  },
  filePreview: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    padding: 8,
    borderRadius: 8,
    marginBottom: 10,
    width: "100%",
  },
  messageRow: {
    alignItems: "flex-end",
  },
  messageAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: "#e3e6eb",
  },
  messageContainer: {
    marginBottom: 14,
    alignSelf: "flex-start",
    maxWidth: "75%", // Giới hạn chiều rộng tối đa
    minWidth: 60,
    flexShrink: 1,
  },
  messageContent: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#f2f4f7",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
    // XÓA maxWidth: "100%" nếu có
  },
  senderName: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1976d2",
    marginBottom: 4,
  },
  messageText: {
    fontSize: 15,
    fontStyle: "normal",
    flexWrap: "wrap",
    color: "#222",
  },
  messageImage: {
    width: 200,
    height: 200,
    borderRadius: 10,
    marginBottom: 5,
  },
  messageVideo: {
    width: 200,
    height: 200,
    borderRadius: 10,
    marginBottom: 5,
  },
  messageFooter: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
    width: "100%",
    justifyContent: "flex-start", // Luôn sát trái
  },
  messageTime: {
    fontSize: 11,
    marginLeft: 2,
    color: "#888",
    opacity: 1,
    textAlign: "left",
  },
  messageStatus: {
    fontSize: 11,
    color: "#bbb",
  },
  replyBox: {
    backgroundColor: "#e9f2fb",
    borderLeftWidth: 3,
    borderLeftColor: "#1976d2",
    padding: 7,
    marginBottom: 5,
    borderRadius: 6,
    alignSelf: "flex-start", // Mặc định cho tin nhắn người khác
  },
  replySenderName: {
    fontWeight: "bold",
    color: "#1976d2",
    marginBottom: 2,
    fontSize: 15,
  },
  replyText: {
    fontStyle: "italic",
    color: "#555",
    flexWrap: "wrap",
    fontSize: 14,
  },
  replyPreview: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#e9f2fb",
    borderLeftWidth: 3,
    borderLeftColor: "#1976d2",
    padding: 7,
    borderRadius: 6,
    marginBottom: 6,
    marginLeft: 2,
  },
  forwardedBox: {
    backgroundColor: "#f5f5f5",
    borderLeftWidth: 3,
    borderLeftColor: "#ff9800",
    padding: 6,
    marginBottom: 4,
    borderRadius: 4,
    maxWidth: "100%",
  },
  pinnedBanner: {
    backgroundColor: "#fff8dc",
    padding: 8,
    borderBottomColor: "#ccc",
    borderBottomWidth: 1,
  },
  pinnedText: {
    fontSize: 14,
    color: "#333",
  },
  pinnedItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  pinnedItemLarge: {
    backgroundColor: "#fffbe7",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#ffe082",
    width: "100%",           // Thêm dòng này để full chiều rộng modal
    alignSelf: "stretch",    // Đảm bảo kéo giãn hết modal
   
  },
  pinnedSender: {
    fontWeight: "bold",
    color: "#1976d2",
    marginBottom: 4,
  },
  pinnedContent: {
    fontSize: 15,
    color: "#333",
    marginBottom: 8,
  },
  unpinButton: {
    alignSelf: "flex-end",
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#ffb300",
    borderRadius: 5,
  },
  unpinButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  pinNotification: {
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: "center",
    marginVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    alignItems: "stretch",   
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
    marginHorizontal: 20,
    width: "90%",            
    alignSelf: "center",    
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#1976d2",
    alignSelf: "center",
  },
  chatItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    width: "100%",
  },
  chatAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },
  chatName: {
    fontSize: 16,
    color: "#222",
  },
  closeButton: {
    marginTop: 16,
    backgroundColor: "#1976d2",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 24,
    alignSelf: "center",
  },
  closeButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  emptyText: {
    color: "#888",
    fontStyle: "italic",
    marginTop: 10,
    alignSelf: "center",
  },
  fileBlock: {
  flexDirection: "row",
  alignItems: "center",
  backgroundColor: "#f5f7fa",
  borderRadius: 10,
  padding: 10,
  marginVertical: 4,
  maxWidth: 340,    // tăng từ 260 lên 340 (hoặc lớn hơn nếu muốn)
  minWidth: 160,    // tăng từ 120 lên 160
  borderWidth: 1,
  borderColor: "#b3c6e7",
},
fileIcon: {
  marginRight: 10,
},
fileName: {
  color: "#1976d2",
  fontWeight: "bold",
  fontSize: 15,
  textDecorationLine: "underline",
},
fileType: {
  color: "#888",
  fontSize: 12,
  marginTop: 2,
},
});