import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f6f8fa",
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    marginTop: 32,
    marginBottom: 28,
    textAlign: "center",
    color: "#222",
  },
  label: {
    fontSize: 16,
    marginBottom: 7,
    color: "#1976d2",
    paddingLeft: 36,
    fontWeight: "600",
  },
  input: {
    borderWidth: 1,
    borderColor: "#d0d7de",
    borderRadius: 12,
    padding: 13,
    fontSize: 16,
    marginBottom: 18,
    backgroundColor: "#fff",
    width: "85%",
    marginLeft: "auto",
    marginRight: "auto",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  genderContainer: {
    flexDirection: "row",
    marginBottom: 18,
    width: "85%",
    marginLeft: "auto",
    marginRight: "auto",
    justifyContent: "space-between",
  },
  genderOption: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    alignItems: "center",
    marginHorizontal: 6,
    backgroundColor: "#f9f9f9",
  },
  genderOptionSelected: {
    borderColor: "#1976d2",
    backgroundColor: "#e3f0fb",
  },
  genderText: {
    fontSize: 16,
    color: "#333",
  },
  genderTextSelected: {
    color: "#1976d2",
    fontWeight: "bold",
  },
  button: {
    backgroundColor: "#1976d2",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 18,
    width: "85%",
    marginLeft: "auto",
    marginRight: "auto",
    shadowColor: "#1976d2",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  secondaryButton: {
    backgroundColor: "#FF6347",
  },
  buttonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
    letterSpacing: 0.2,
  },
  avatarButton: {
    backgroundColor: "#FF6347",
    padding: 10,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
    width: "60%",
    alignSelf: "center",
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    marginTop: 10,
    alignSelf: "center",
    marginBottom: 20,
    borderWidth: 3,
    borderColor: "#1976d2",
    backgroundColor: "#e3eaf2",
  },
  errorText: {
    color: "#e53935",
    fontSize: 13,
    marginBottom: 8,
    marginLeft: 38,
    marginTop: -10,
    fontStyle: "italic",
    fontWeight: "500",
    textAlign: "left",
  },
});